---
deployment:
 tasks:
 - export DEPLOYPATH=/home/prasecte/public_html/netrotechnologies.com/
 - /bin/cp -R css $DEPLOYPATH
 - /bin/cp -R fonts $DEPLOYPATH
 - /bin/cp -R images $DEPLOYPATH
 - /bin/cp -R js $DEPLOYPATH
 - /bin/cp -R public $DEPLOYPATH
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp .htaccess $DEPLOYPATH